{% set name = "yattag" %}
{% set version = "1.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 70c790aa7a4f5f4f78305404ca3a4488f83c96f28714a4f8b96e69d71cd8736b

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - yattag

about:
  home: http://www.yattag.org
  license: LGPL-2.1
  license_family: LGPL
  license_file: LICENSE.txt
  summary: Generate HTML or XML in a pythonic way. Pure python alternative to web template engines.Can fill HTML forms with default values and error messages.

extra:
  recipe-maintainers:
    - pmgrafe
