travis:
  secure:
    BINSTAR_TOKEN: J+pKSHIyNZfM2hCCPErqjNqcjettJ11RiFHZRoxPrENesWYlXNSlgM6L7W9yAumaqfS5m82Fkn42qOZfaA6MDEVepy69zcWikxUYYBNRVKHAgnY0Pawgl6m5ALYMT2fL15OTxhnqwxwzCek8FJOtL3EnFBWVOkeEiXZ3gC4otpoPQfCTKTyrB19WdbgprwcNQ0YkLo5s0AQL74KX1Cdj1NNMlcddIOXc6/ed1Ceo/I53NfQdDBEUq9lV1loHRidDBYgvfY6nZL0+a//wd5zqYxJTw4rNhPbqvCq2CGW8dNOZq9u4ADwGijcgj3NezNSvZm+hpOz93XYGF9T5kBc/XXozkjkjRA+GeC7xNpGFAoCb7QlQ4wJOKuprT41EKK5v2bzSarMf+RTt7EuBi0/WY+3ZjecmavKPtLQkrYdE86ZILFAQhDOZY/sJ4b+bnthjZmYcuStB9gltJ3rFHs+hLiQ1o1i+zQLnJBxlDZsiNr/kLAwVsqDzAHXr6fyVp1OsqwSyhRjpQ0IyPL2RskD+9I86YPCWYJXJgtDgSbp1E7YelsrMCmAglLE7VprJRx45GN6RPfRENWLygy4NedJZHQW9hsUurM0Re9fjBIzqmwtbRQa1/2ilflKLfv2Z0PpVwkpiqOVWJ3Cw/iBAPEJamtiYSnfpwITE+L7G5wcTCVs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
