travis:
  secure:
    BINSTAR_TOKEN: ANO27jdzFJYChiysxA0PXUbiGahsvOWQMl80Bm04mJgv5czsjQdkuBRfb6dR+0e9MSnfNHezoEQNIDKk9MsUg9MaX10tmYUfVeg0Xl4CaxCVV0vRr6HIPvLfH/KF2d9XHTtLvyW113DHHLPdukLBf0pSEYm3owsHk2SK5vqWQ4aRHgZxNw6t5jQI2JweAHJQIxECDLIia2RA3ei1VUBQngCGEo2TduhhgCUTdDZHWNXQybYjzDOvGmPwKk3UcGct4beD1TqtazgLgthGJ7zxs+/5S051P5NN+0HA1R8KA1TE0s0Nzb9PKW5of+9CIjYxOpuBg3Mdkds2ZbN8f0yzK5M/jKRWBIriPxfvEi5GbjFSiC8DUocvyCWiwULLO67jO0Huu5prXGgegcqm0N2i+B5sPXVRw7R3nnsxPLsBUj9fgAj0uv3JMqe89IPY0CRPZBvhacXNYWwQTs4k4YUbk6CeHsfAhAASet95jTL/zZ6hqqwUprz9RB5LuaxzLRkIO6Z1YP61yH1YwXfwfwxpfTtfvXe848nm98F7SwX+Xgzy9tevRvi1ueQXKJUw2rafBsaL9fXdaPBmwpMX8i0GrkNL5bWIbdgt7jntV5Kaurzq6MsQztLPbKZK/6qEgN2aXwiLkvRxxSK1LPXe56Zi5eQHLBFxiE3pKGgHVNAHrHE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
